# Generated by Django 5.2.7 on 2025-10-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('cupo_disponible', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_actividad', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('dni', models.IntegerField()),
                ('edad', models.IntegerField()),
                ('cant_personas', models.IntegerField()),
                ('talle', models.CharField(blank=True, max_length=10, null=True)),

            ],
        ),
    ]
