# Generated by Django 5.2.7 on 2025-10-18 15:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('dni', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('talle', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='talle',
        ),
        migrations.CreateModel(
            name='InscripcionPorPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.inscripcion')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.persona')),
            ],
        ),
    ]
